### ISSUE TITLE
Loading the app

### ISSUE THREAD

**Issue by susphine** [PopcornTime-CE/desktop#30] opened 2016-01-29 01:43 UTC
When loading the original builds it's nearly instant, I'm experimenting and trying to develop an experimental project.

Why is the load time so slow? It takes like 1 minute to load the application while the original ones is instant. With loading I mean time between executing the app and it showing up.
Both in npm start and after building. How can we make our own auto updater aswell?

**Comment by YIFYtorrents** [comment] 2016-02-03 12:57
We had some problems with the API server due to ddos attacks. However, the [yts.ph](http://yts.ph) group just bought 10 new servers, so the issue is fixed now.

It's recommend to change Movie API Endpoint to http://yts.ph if you have an Belgium ISP or Popcorn Time CE YIFY may not work correctly.

**Closed as completed** 2016-02-24 03:04 UTC
